# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headofdept', models.BooleanField()),
                ('permanent', models.BooleanField()),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='leave date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.IntegerField()),
                ('casual', models.IntegerField(default=15)),
                ('earned', models.IntegerField()),
                ('extras', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='typeofleave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.LeaveType'),
        ),
    ]
