# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavesremain',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
