# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavesRemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ManyToManyField(to='leaves.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='casual',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='earned',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='medical',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='name',
            field=models.CharField(default='somevalue', max_length=20),
        ),
        migrations.AddField(
            model_name='leavesremain',
            name='typeofleave',
            field=models.ManyToManyField(to='leaves.LeaveType'),
        ),
    ]
